name: CI for mature

on:
  push:
    branches:
      - "main"
    paths:
      - "packages/mature/**"
      - ".github/workflows/ci_mature.yml"
      - "yarn.lock"
  pull_request:
    paths:
      - "packages/mature/**"
      - ".github/workflows/ci_mature.yml"
      - "yarn.lock"

jobs:
  setup:
    name: Setup

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/mature

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.25.0

      - name: Cache
        uses: actions/cache@v2
        id: cache-go
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download
        if: steps.cache-go.outputs.cache-hit != 'true'
        run: go mod download

  lint:
    needs: setup

    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/mature

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.25.0

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.39
          working-directory: packages/mature
          skip-go-installation: true

  test:
    needs: setup
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/mature

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.25.0

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        run: make test

  build:
    needs: setup

    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/mature

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.25.0

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build for development
        run: make cmd/mature/mature

      - name: Build for production
        run: make dist
