name: CI for notify

on:
  push:
    branches:
      - "main"
    paths:
      - "packages/notify/**"
      - ".github/workflows/ci_notify.yml"
      - "yarn.lock"
  pull_request:
    paths:
      - "packages/notify/**"
      - ".github/workflows/ci_notify.yml"
      - "yarn.lock"

jobs:
  setup:
    name: Setup

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/notify

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Cache
        uses: actions/cache@v2
        id: cache-go
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download
        if: steps.cache-go.outputs.cache-hit != 'true'
        run: go mod download

  lint:
    needs: setup

    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/notify

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.39
          working-directory: packages/notify
          skip-go-installation: true

  test:
    needs: setup
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/notify

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        run: make test

  build:
    needs: setup

    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/notify

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build for development
        run: make cmd/notify/notify

      - name: Build for production
        run: make dist
